### PR TITLE
Fix settings bug

### LINKED ISSUE #96: Preserve entered data in global settings
In the Settings panel, you enter a module name and then directly go to the language dialog to select a language. When you return back to the Settings panel, the module name that was entered earlier is not shown there anymore. We have to enter the module name again before pressing the Save button. Current workaround is for the user to press Save before going to the language dialog.

Fix here is to prevent pitfall of user losing their data in the initial use of settings

### PR DESCRIPTION
**Pull request by marthacryan**
Fixes #96. The settings for the module name are exclusively stored in the browser memory. The language is stored as follows:
* If opening a blank pipeline:
  * If there is a language stored in the browser memory, use that language
  * Else use English
* If opening an existing pipeline:
  * If there is a language specified in the pipeline, use that language
  * Else use rules from first bullet

### CODE REVIEW

File: src/nlp-visual-editor/nlp-visual-editor.jsx [hunk 1]
```diff
@@ -100,13 +104,15 @@ class VisualEditor extends React.Component {
...
       showSettings: false,
-      editorSettings: localStorage.getItem('nlpEditorSettings') ? JSON.parse(localStorage.getItem('nlpEditorSettings')) : {
-        moduleName: 'elyraNLPCanvas',
-        language: 'en'
-      }
+      editorSettings: localStorage.getItem('nlpEditorSettings')
+        ? JSON.parse(localStorage.getItem('nlpEditorSettings'))
+        : {
+            moduleName: 'elyraNLPCanvas',
+            language: 'en',
```
Comment (laurachiticariu) [inline src/nlp-visual-editor/nlp-visual-editor.jsx:111]: Would it be possible to make 'en' a constant, as it is used repeatedly in multiple places? It could be called "default_language" or something like this, and replace all usages of `en` with the `default_language` constant.

File: src/nlp-visual-editor/nlp-visual-editor.jsx [hunk 2]
```diff
@@ -257,7 +263,7 @@ class VisualEditor extends React.Component {
       body: JSON.stringify({
         workingId,
         payload,
-        language: this.getCurrentLanguage(),
+        language: this.getCurrentLanguage() ?? 'en',
```
Comment (laurachiticariu) [inline src/nlp-visual-editor/nlp-visual-editor.jsx:266]: 'en' as constant - see the earlier comment

File: src/nlp-visual-editor/nlp-visual-editor.jsx [hunk 3]
```diff
@@ -790,16 +816,23 @@ class VisualEditor extends React.Component {
...
+            'nlpEditorSettings',
+            JSON.stringify(editorSettings),
+          );
         }}
         onRequestClose={() => {
           this.setState({ languageSelectModal: false });
         }}
         languages={languages}
-        currentLanguage={this.getCurrentLanguage()}
+        currentLanguage={this.getCurrentLanguage() ?? 'en'}
```
Comment (laurachiticariu) [inline src/nlp-visual-editor/nlp-visual-editor.jsx:835]: 'en' as constant - see the earlier comment

File: src/nlp-visual-editor/nlp-visual-editor.jsx [hunk 4]
```diff
@@ -740,35 +753,48 @@ class VisualEditor extends React.Component {
...
+                );
+                this.setCurrentLanguage(this.state.editorSettings.language);
+              } else if (closeSource === 'cancel') {
+                this.setState({
+                  showSettings: false,
+                  editorSettings: localStorage.getItem('nlpEditorSettings')
+                    ? JSON.parse(localStorage.getItem('nlpEditorSettings'))
+                    : {
+                        moduleName: 'elyraNLPCanvas',
+                        language: 'en',
```
Comment (laurachiticariu) [inline src/nlp-visual-editor/nlp-visual-editor.jsx:781]: 'en' as constant - see the earlier comment

**Review by laurachiticariu — CHANGES_REQUESTED** [review]
Thanks, Martha! Just a small comment

**Comment by laurachiticariu** [comment]
@marthacryan can you rebase on `main` to solve the conflicts?

**Review by laurachiticariu — APPROVED** [review]
